//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQL.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SQL.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE Students (id int, FirstName varchar(50), LastName varchar(50), PRIMERY KEY (id) );
        ///    INSERT INTO Students VALUES (&quot;Slavik&quot; , &quot;Ivanenko&quot; );
        ///    INSERT INTO Students VALUES (&quot;Danil&quot; , &quot;Gigamovsky&quot; );
        ///    INSERT INTO Students VALUES (&quot;Max&quot; , &quot;Moskalchyk&quot; );
        ///    INSERT INTO Students VALUES (&quot;Azim&quot; , &quot;Plathanov&quot; );
        ///    INSERT INTO Students VALUES (&quot;Max&quot; , &quot;Osypenok&quot; );
        ///    INSERT INTO Students VALUES (&quot;OLEH&quot; , &quot;OLEXandrov&quot; );
        ///
        ///CREATE TABLE Marks (id int, value int, idStud int, subj varchar [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Avtor1 {
            get {
                return ResourceManager.GetString("Avtor1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REATE  TABLE  STUDENTS  (ID  INT,  FIRSTNAME  varchar(50),  LASTNAME  varchar(50),  PRIMERY  KEY  (ID)  );
        ///        INSERT  INTO  STUDENTS  VALUES  (&quot;Slavik&quot;  ,  &quot;Ivanenko&quot;  );
        ///        INSERT  INTO  STUDENTS  VALUES  (&quot;Danil&quot;  ,  &quot;Gigamovsky&quot;  );
        ///        INSERT  INTO  STUDENTS  VALUES  (&quot;Max&quot;  ,  &quot;Moskalchyk&quot;  );
        ///        INSERT  INTO  STUDENTS  VALUES  (&quot;Azim&quot;  ,  &quot;Plathanov&quot;  );
        ///        INSERT  INTO  STUDENTS  VALUES  (&quot;Max&quot;  ,  &quot;Osypenok&quot;  );
        ///        INSERT  INTO  STUDENTS  VALUES  (&quot;OLEH&quot;  ,  &quot;OLEXa [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Avtor2 {
            get {
                return ResourceManager.GetString("Avtor2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;BNF xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;rules&gt;
        ///    &lt;Rule&gt;
        ///      &lt;name&gt;&amp;lt;Програма&amp;gt;&lt;/name&gt;
        ///      &lt;rule&gt;{&amp;lt;Транзакція&amp;gt;;}&amp;lt;Транзакція&amp;gt;[&apos;;&apos;]&lt;/rule&gt;
        ///    &lt;/Rule&gt;
        ///    &lt;Rule&gt;
        ///      &lt;name&gt;&amp;lt;Space&amp;gt;&lt;/name&gt;
        ///      &lt;rule&gt;&apos; &apos;{&apos; &apos;}&lt;/rule&gt;
        ///    &lt;/Rule&gt;
        ///    &lt;Rule&gt;
        ///      &lt;name&gt;&amp;lt;Команда&amp;gt;&lt;/name&gt;
        ///      &lt;rule /&gt;
        ///    &lt;/Rule&gt;
        ///  &lt;/rules&gt;
        ///  &lt;formatter /&gt;
        ///  &lt;length&gt;3&lt;/length&gt;
        ///&lt;/BNF&gt;.
        /// </summary>
        public static string BNF {
            get {
                return ResourceManager.GetString("BNF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE Students (id int, FirstName varchar(50), LastName varchar(50), PRIMERY KEY (id) );
        ///    INSERT INTO Students VALUES (&quot;Slavik&quot; , &quot;Ivanenko&quot; );
        ///    INSERT INTO Students VALUES (&quot;Danil&quot; , &quot;Gigamovsky&quot; );
        ///    INSERT INTO Students VALUES (&quot;Max&quot; , &quot;Moskalchyk&quot; );
        ///    INSERT INTO Students VALUES (&quot;Azim&quot; , &quot;Plathanov&quot; );
        ///    INSERT INTO Students VALUES (&quot;Max&quot; , &quot;Osypenok&quot; );
        ///    INSERT INTO Students VALUES (&quot;OLEH&quot; , &quot;OLEXandrov&quot; );
        ///
        ///CREATE TABLE Marks (id int, value int, idStud int, subj varchar [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
    }
}
